### ISSUE TITLE
is vcomp still necessary?

### ISSUE THREAD

**Issue by mkborregaard** [ChrisRackauckas/VectorizedRoutines.jl#11]
In 0.5 you can use conditionals in comprehensions:
```
Int[i^2 for i in 1:10 if i % 2 == 0] #Int[4, 16, 36, 64, 100]
```

**Comment by ChrisRackauckas** [comment]
Probably not. It can be removed now. It was added long before v0.5.

**Comment by mkborregaard** [comment]
At least all the tests and examples work simply by extending the comprehension and replacing `when` with `if`. It would be a simple matter of removing the Python submodule. Just a bit sad, in a sense.

**Comment by ChrisRackauckas** [comment]
deleted
