### ISSUE TITLE
accumarray doesn't give same results as MATLAB 2017a documentation

### ISSUE THREAD

**Issue by kmundnic** [ChrisRackauckas/VectorizedRoutines.jl#13]
I'm working in Julia v0.5.2, VectorizedRoutines v0.0.2.

If I try the first example of accumarray in MATLAB's 2017a documentation, I get:
```
subs = [1; 2; 4; 2; 4];
A = accumarray(subs,1)
A = 

     1
     2
     0
     2
```
In Julia,
```
subs = [1; 2; 4; 2; 4];
A = Matlab.accumarray(subs,1)
A = 

     1
     0
     0
     0
```

**Comment by ChrisRackauckas** [comment]
I actually didn't know you could do it in MATLAB with `val` a number. I always thought it had to be an array of similar size. I can add a dispatch for this pretty easily.

**Comment by ChrisRackauckas** [comment]
Fixed on master.

**Comment by kmundnic** [comment]
Thanks! That was really fast :-)
