### ISSUE TITLE
Matlab implementation of unique

### ISSUE THREAD

**Issue by ueliwechsler** [ChrisRackauckas/VectorizedRoutines.jl#16]
I was looking for a julia implementation of the  Matlab function `[C, ia, ic] = unique(A)` [https://www.mathworks.com/help/matlab/ref/unique.html](url).
I found the discussion in [https://github.com/JuliaLang/julia/issues/1845](url) with a implementation of the function in [https://github.com/AndyGreenwell/GroupSlices.jl/pull/9](url) which is pretty close to the actual implementation in matlab (the return vector ic of `groupslices(A,1)` is not the same as `ic` in matlab). 

Would you consider merging this function or accepting a pull request into VectorizedRoutines.jl since this package makes a great tool for converting matlab code to julia.

**Comment by ChrisRackauckas** [comment]
Yeah,I would merge it.
