### ISSUE TITLE
Installing VectorizedRoutines broke dependencies

### ISSUE THREAD

**Issue by drbergman** [ChrisRackauckas/VectorizedRoutines.jl#20]
I installed VectorizedRoutines.jl using the Package manager in the Julia REPL running 1.9.2. A bunch of issues showed up at that point, including not being able to compile the Revise.jl and JLD2.jl packages. After uninstalling VectorizedRoutines.jl and updating all packages, everything worked as before.

Not sure if this package is being maintained, so I didn't look further into what caused the issues.

**Comment by ChrisRackauckas** [comment]
I'm surprised it still installs. I haven't touched it in 4 or 5 years, pre Julia v1.0 I thought? I'll archive it right now.
