### ISSUE TITLE
`pairwise_map()` function?

### ISSUE THREAD

**Issue by mkborregaard** [ChrisRackauckas/VectorizedRoutines.jl#8]
[Here](https://discourse.julialang.org/t/generic-function-for-pairwise-operations/1041) we discussed the possibility of adding a generic function for pairwise operations on all elements of collections. The obvious thing is to base this on the framework for pairwise distances in [Distances.jl](https://github.com/JuliaStats/Distances.jl), which would be to do something like this:
```julia
function pairwise!(r::AbstractMatrix, f::Function, a::AbstractVector)
    n = length(a)
    size(r) == (n, n) || throw(DimensionMismatch("Incorrect size of r."))
    for j = 1 : n
        aj = a[j]
        for i = 1 : n
            @inbounds r[i,j] = f(a[i], aj)
        end
    end
    r
end

function pairwise(f::Function, a::AbstractVector)
    m = length(a)
    first = f(a[1], a[1])
    m < 2 && return first
    r = Matrix{typeof(first)}(m, m)
    pairwise!(r, f, a)
end

a = randn(4)
f(x,y) = x + y
pairwise(f,a)
```
But there are lots of things to consider:

1. what should the return type be? A Vector or a Matrix?
2. what about symmetric functions (like the one in the example) - should they return a `Symmetric` (care must then be taken to avoid type instability)?
3. what about vectorized functions - e.g. it would be nice to do `pairwise(sum, a)` but that is not possible with the above implementation
4. how might this be extended to multidimensional arrays - would it be necessary with a `pairwise_slices` function?
5. the `pairwise` name is already used in Distances.jl - this might not be a problem as the signature is different (they require a Distance type object in place of the function) but the interfaces should be aligned in case that name is chosen.

**Comment by mkborregaard** [comment]
Or would one prefer the vector operations directly:
```
function pairwise!(r::AbstractMatrix, f::Function, a::AbstractVector)
    n = length(a)
    size(r) == (n, n) || throw(DimensionMismatch("Incorrect size of r."))
    for j = 1 : n
        for i = 1 : n
            @inbounds r[i,j] = f(a[i,j])
        end
    end
    r
end
```

**Comment by ChrisRackauckas** [comment]
1. Matrix, it makes much more sense for indexing.

2. Yes, a `Symmetric` would be a triangular matrix (that type would need to be implemented from a Vector) with an indexing scheme which makes it efficient. Optional argument with `Val{true}` vs `Val{false}` would work (which is like how matrix pivoting is turned on/off). Users could then set that in code, but the true/false shouldn't be computed dynamically for it to work.

3. `pairwise(sum, a)`? What would that mean?

4.  Yeah, choose a dimension and pairwise on those?

5. `pairwise_apply`? I don't think there's a reason to add the dependency there.

**Comment by mkborregaard** [comment]
1. I tend to agree - I'd just like to be able to do `mean(pairwise(f, a))`, which wouldn't work on a `Matrix` (you'd need to avoid the diagonal). It would work if the function returned a `LowerTriangular` though so maybe that is a good alternative to `Symmetric`?
2. `Symmetric` is defined in `Base`, I don't think we'd like to override that? I'll implement the idea of letting the user define if the function is symmetric by an optional argument.
3. The same as `f(x,y) = x+y; pairwise(f, a)` in the above syntax. `sum`, `mean`, `diff` etc are defined on arrays, not two input arguments. A solution might be
```julia
r[i,j] = try
        f(a[[i, j]])
    catch
        f(a[i], aj)
end
```
?

4. Cool.
5. Yeah or `pairwise_map`. Or ignore that the names are the same.

**Comment by mkborregaard** [comment]
I am almost done with the PR, where I have made efficient support for various input/output types. But just realized that if performance isn't critical, it can generally just be expressed as `f.(a,a')` where `f` is the function and `a` is a `Vector`.

**Comment by ChrisRackauckas** [comment]
Then assume performance is critical :).

**Comment by mkborregaard** [comment]
Right, here you are: https://github.com/ChrisRackauckas/VectorizedRoutines.jl/pull/9

Here are some benchmarks to address the last concern (results may change with RowVectors in 0.6):
```julia
using VectorizedRoutines.Julia, BenchmarkTools
f(x,y) = 2x^y
a = 1:20
@benchmark f.(a,a')
BenchmarkTools.Trial: 
  memory estimate:  4.86 kb
  allocs estimate:  41
  --------------
  minimum time:     16.551 μs (0.00% GC)
  median time:      18.604 μs (0.00% GC)
  mean time:        24.129 μs (3.16% GC)
  maximum time:     5.324 ms (96.51% GC)
  --------------
  samples:          10000
  evals/sample:     1
  time tolerance:   5.00%
  memory tolerance: 1.00%

@benchmark pairwise(f,a)
BenchmarkTools.Trial: 
  memory estimate:  3.44 kb
  allocs estimate:  5
  --------------
  minimum time:     3.185 μs (0.00% GC)
  median time:      3.328 μs (0.00% GC)
  mean time:        4.487 μs (8.08% GC)
  maximum time:     573.347 μs (97.92% GC)
  --------------
  samples:          10000
  evals/sample:     8
  time tolerance:   5.00%
  memory tolerance: 1.00%

@benchmark pairwise(f,a, symmetric = true)
BenchmarkTools.Trial: 
  memory estimate:  3.56 kb
  allocs estimate:  7
  --------------
  minimum time:     2.489 μs (0.00% GC)
  median time:      2.687 μs (0.00% GC)
  mean time:        4.142 μs (12.21% GC)
  maximum time:     635.482 μs (98.31% GC)
  --------------
  samples:          10000
  evals/sample:     9
  time tolerance:   5.00%
  memory tolerance: 1.00%
```
More details on the PR. As `f` is fairly trivial, the speedup of `symmetric` is offset by the lack of locality.

**Comment by mkborregaard** [comment]
Solved in https://github.com/ChrisRackauckas/VectorizedRoutines.jl/pull/9
